# apiVersion: v1
# kind: Service
# metadata:
#   name: api
#   namespace: three-tier
# spec: 
#   ports:
#   - port: 3500
#     protocol: TCP
#   type: ClusterIP
#   selector:
#     role: api

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec:
  type: NodePort
  selector:
    role: api
  ports:
    - port: 3500
      targetPort: 3500
      nodePort: 30002
      protocol: TCP    
