# apiVersion: v1
# kind: Service
# metadata: 
#   name: frontend
#   namespace: three-tier
# spec:
#   ports:
#   - port: 3000
#     protocol: TCP
#   type: ClusterIP
#   selector:
#     role: frontend

apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  type: NodePort
  selector:
    role: frontend
  ports:
    - port: 3000        # service port
      targetPort: 3000  # container port
      nodePort: 30080   # external port (must be in 30000–32767)
      protocol: TCP
